"""empty message

Revision ID: 24e494ff13d
Revises: 546323bed98
Create Date: 2015-06-29 14:08:56.943768

"""

# revision identifiers, used by Alembic.
revision = '24e494ff13d'
down_revision = '546323bed98'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'boards', ['shortname'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'boards', type_='unique')
    ### end Alembic commands ###
